//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from GrammarGenLang.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace SharpIrcBot.Plugins.GrammarGen.Lang {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public partial class GrammarGenLangLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, Whitespaces=16, 
		Comments=17, LineComments=18, EscapedString=19, Identifier=20, Number=21;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "T__14", "Whitespaces", "Comments", 
		"LineComments", "EscapedString", "Identifier", "Number", "HexD", "Whitespace"
	};


	public GrammarGenLangLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public GrammarGenLangLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "':'", "';'", "'{'", "','", "'}'", "'|'", "'!'", "'<'", "'>'", "'('", 
		"')'", "'['", "']'", "'*'", "'+'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, "Whitespaces", "Comments", "LineComments", "EscapedString", 
		"Identifier", "Number"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "GrammarGenLang.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static GrammarGenLangLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x17', '\xA0', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', 
		'\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', 
		'\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x6', '\x11', 'Q', '\n', '\x11', '\r', '\x11', '\xE', '\x11', 'R', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\a', '\x12', '[', '\n', '\x12', '\f', '\x12', '\xE', '\x12', 
		'^', '\v', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\a', '\x13', 'i', '\n', '\x13', '\f', '\x13', '\xE', '\x13', 
		'l', '\v', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\a', 
		'\x14', '\x8A', '\n', '\x14', '\f', '\x14', '\xE', '\x14', '\x8D', '\v', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\a', 
		'\x15', '\x93', '\n', '\x15', '\f', '\x15', '\xE', '\x15', '\x96', '\v', 
		'\x15', '\x3', '\x16', '\x6', '\x16', '\x99', '\n', '\x16', '\r', '\x16', 
		'\xE', '\x16', '\x9A', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\\', '\x2', '\x19', '\x3', '\x3', '\x5', '\x4', '\a', 
		'\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', 
		'\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', 
		'\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', 
		'\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x2', '/', '\x2', '\x3', 
		'\x2', '\t', '\x4', '\x2', '\f', '\f', '\xF', '\xF', '\x4', '\x2', '$', 
		'$', '^', '^', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', 
		'\x6', '\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', '|', 
		'\x3', '\x2', '\x32', ';', '\x5', '\x2', '\x32', ';', '\x43', 'H', '\x63', 
		'h', '\x4', '\x2', '\v', '\xF', '\"', '\"', '\x2', '\xA7', '\x2', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x3', '\x31', 
		'\x3', '\x2', '\x2', '\x2', '\x5', '\x33', '\x3', '\x2', '\x2', '\x2', 
		'\a', '\x35', '\x3', '\x2', '\x2', '\x2', '\t', '\x37', '\x3', '\x2', 
		'\x2', '\x2', '\v', '\x39', '\x3', '\x2', '\x2', '\x2', '\r', ';', '\x3', 
		'\x2', '\x2', '\x2', '\xF', '=', '\x3', '\x2', '\x2', '\x2', '\x11', '?', 
		'\x3', '\x2', '\x2', '\x2', '\x13', '\x41', '\x3', '\x2', '\x2', '\x2', 
		'\x15', '\x43', '\x3', '\x2', '\x2', '\x2', '\x17', '\x45', '\x3', '\x2', 
		'\x2', '\x2', '\x19', 'G', '\x3', '\x2', '\x2', '\x2', '\x1B', 'I', '\x3', 
		'\x2', '\x2', '\x2', '\x1D', 'K', '\x3', '\x2', '\x2', '\x2', '\x1F', 
		'M', '\x3', '\x2', '\x2', '\x2', '!', 'P', '\x3', '\x2', '\x2', '\x2', 
		'#', 'V', '\x3', '\x2', '\x2', '\x2', '%', '\x64', '\x3', '\x2', '\x2', 
		'\x2', '\'', 'o', '\x3', '\x2', '\x2', '\x2', ')', '\x90', '\x3', '\x2', 
		'\x2', '\x2', '+', '\x98', '\x3', '\x2', '\x2', '\x2', '-', '\x9C', '\x3', 
		'\x2', '\x2', '\x2', '/', '\x9E', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\x32', '\a', '<', '\x2', '\x2', '\x32', '\x4', '\x3', '\x2', '\x2', '\x2', 
		'\x33', '\x34', '\a', '=', '\x2', '\x2', '\x34', '\x6', '\x3', '\x2', 
		'\x2', '\x2', '\x35', '\x36', '\a', '}', '\x2', '\x2', '\x36', '\b', '\x3', 
		'\x2', '\x2', '\x2', '\x37', '\x38', '\a', '.', '\x2', '\x2', '\x38', 
		'\n', '\x3', '\x2', '\x2', '\x2', '\x39', ':', '\a', '\x7F', '\x2', '\x2', 
		':', '\f', '\x3', '\x2', '\x2', '\x2', ';', '<', '\a', '~', '\x2', '\x2', 
		'<', '\xE', '\x3', '\x2', '\x2', '\x2', '=', '>', '\a', '#', '\x2', '\x2', 
		'>', '\x10', '\x3', '\x2', '\x2', '\x2', '?', '@', '\a', '>', '\x2', '\x2', 
		'@', '\x12', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\a', '@', '\x2', 
		'\x2', '\x42', '\x14', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\a', 
		'*', '\x2', '\x2', '\x44', '\x16', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\x46', '\a', '+', '\x2', '\x2', '\x46', '\x18', '\x3', '\x2', '\x2', 
		'\x2', 'G', 'H', '\a', ']', '\x2', '\x2', 'H', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', 'I', 'J', '\a', '_', '\x2', '\x2', 'J', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', 'K', 'L', '\a', ',', '\x2', '\x2', 'L', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', 'M', 'N', '\a', '-', '\x2', '\x2', 'N', ' ', '\x3', '\x2', '\x2', 
		'\x2', 'O', 'Q', '\x5', '/', '\x18', '\x2', 'P', 'O', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'R', '\x3', '\x2', '\x2', '\x2', 'R', 'P', '\x3', '\x2', '\x2', 
		'\x2', 'R', 'S', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\x3', '\x2', '\x2', 
		'\x2', 'T', 'U', '\b', '\x11', '\x2', '\x2', 'U', '\"', '\x3', '\x2', 
		'\x2', '\x2', 'V', 'W', '\a', '\x31', '\x2', '\x2', 'W', 'X', '\a', ',', 
		'\x2', '\x2', 'X', '\\', '\x3', '\x2', '\x2', '\x2', 'Y', '[', '\v', '\x2', 
		'\x2', '\x2', 'Z', 'Y', '\x3', '\x2', '\x2', '\x2', '[', '^', '\x3', '\x2', 
		'\x2', '\x2', '\\', ']', '\x3', '\x2', '\x2', '\x2', '\\', 'Z', '\x3', 
		'\x2', '\x2', '\x2', ']', '_', '\x3', '\x2', '\x2', '\x2', '^', '\\', 
		'\x3', '\x2', '\x2', '\x2', '_', '`', '\a', ',', '\x2', '\x2', '`', '\x61', 
		'\a', '\x31', '\x2', '\x2', '\x61', '\x62', '\x3', '\x2', '\x2', '\x2', 
		'\x62', '\x63', '\b', '\x12', '\x2', '\x2', '\x63', '$', '\x3', '\x2', 
		'\x2', '\x2', '\x64', '\x65', '\a', '\x31', '\x2', '\x2', '\x65', '\x66', 
		'\a', '\x31', '\x2', '\x2', '\x66', 'j', '\x3', '\x2', '\x2', '\x2', 'g', 
		'i', '\n', '\x2', '\x2', '\x2', 'h', 'g', '\x3', '\x2', '\x2', '\x2', 
		'i', 'l', '\x3', '\x2', '\x2', '\x2', 'j', 'h', '\x3', '\x2', '\x2', '\x2', 
		'j', 'k', '\x3', '\x2', '\x2', '\x2', 'k', 'm', '\x3', '\x2', '\x2', '\x2', 
		'l', 'j', '\x3', '\x2', '\x2', '\x2', 'm', 'n', '\b', '\x13', '\x2', '\x2', 
		'n', '&', '\x3', '\x2', '\x2', '\x2', 'o', '\x8B', '\a', '$', '\x2', '\x2', 
		'p', 'q', '\a', '^', '\x2', '\x2', 'q', '\x8A', '\a', '$', '\x2', '\x2', 
		'r', 's', '\a', '^', '\x2', '\x2', 's', '\x8A', '\a', '^', '\x2', '\x2', 
		't', 'u', '\a', '^', '\x2', '\x2', 'u', 'v', '\a', 'w', '\x2', '\x2', 
		'v', 'w', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\x5', '-', '\x17', '\x2', 
		'x', 'y', '\x5', '-', '\x17', '\x2', 'y', 'z', '\x5', '-', '\x17', '\x2', 
		'z', '{', '\x5', '-', '\x17', '\x2', '{', '\x8A', '\x3', '\x2', '\x2', 
		'\x2', '|', '}', '\a', '^', '\x2', '\x2', '}', '~', '\a', 'W', '\x2', 
		'\x2', '~', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x80', '\x5', 
		'-', '\x17', '\x2', '\x80', '\x81', '\x5', '-', '\x17', '\x2', '\x81', 
		'\x82', '\x5', '-', '\x17', '\x2', '\x82', '\x83', '\x5', '-', '\x17', 
		'\x2', '\x83', '\x84', '\x5', '-', '\x17', '\x2', '\x84', '\x85', '\x5', 
		'-', '\x17', '\x2', '\x85', '\x86', '\x5', '-', '\x17', '\x2', '\x86', 
		'\x87', '\x5', '-', '\x17', '\x2', '\x87', '\x8A', '\x3', '\x2', '\x2', 
		'\x2', '\x88', '\x8A', '\n', '\x3', '\x2', '\x2', '\x89', 'p', '\x3', 
		'\x2', '\x2', '\x2', '\x89', 'r', '\x3', '\x2', '\x2', '\x2', '\x89', 
		't', '\x3', '\x2', '\x2', '\x2', '\x89', '|', '\x3', '\x2', '\x2', '\x2', 
		'\x89', '\x88', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8D', '\x3', '\x2', 
		'\x2', '\x2', '\x8B', '\x89', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', 
		'\x3', '\x2', '\x2', '\x2', '\x8C', '\x8E', '\x3', '\x2', '\x2', '\x2', 
		'\x8D', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\a', '$', 
		'\x2', '\x2', '\x8F', '(', '\x3', '\x2', '\x2', '\x2', '\x90', '\x94', 
		'\t', '\x4', '\x2', '\x2', '\x91', '\x93', '\t', '\x5', '\x2', '\x2', 
		'\x92', '\x91', '\x3', '\x2', '\x2', '\x2', '\x93', '\x96', '\x3', '\x2', 
		'\x2', '\x2', '\x94', '\x92', '\x3', '\x2', '\x2', '\x2', '\x94', '\x95', 
		'\x3', '\x2', '\x2', '\x2', '\x95', '*', '\x3', '\x2', '\x2', '\x2', '\x96', 
		'\x94', '\x3', '\x2', '\x2', '\x2', '\x97', '\x99', '\t', '\x6', '\x2', 
		'\x2', '\x98', '\x97', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\x3', 
		'\x2', '\x2', '\x2', '\x9A', '\x98', '\x3', '\x2', '\x2', '\x2', '\x9A', 
		'\x9B', '\x3', '\x2', '\x2', '\x2', '\x9B', ',', '\x3', '\x2', '\x2', 
		'\x2', '\x9C', '\x9D', '\t', '\a', '\x2', '\x2', '\x9D', '.', '\x3', '\x2', 
		'\x2', '\x2', '\x9E', '\x9F', '\t', '\b', '\x2', '\x2', '\x9F', '\x30', 
		'\x3', '\x2', '\x2', '\x2', '\n', '\x2', 'R', '\\', 'j', '\x89', '\x8B', 
		'\x94', '\x9A', '\x3', '\x2', '\x3', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace SharpIrcBot.Plugins.GrammarGen.Lang
