language: csharp
solution: SharpIrcBot.sln
mono:
  - 4.5.0
before_install:
  - git submodule update --init --recursive
install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono nuget.exe restore SharpIrcBot.sln
  - mono nuget.exe install xunit.runner.console -Prerelease -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SharpIrcBot.sln
  - ./Tests/runtests.sh
