language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
before_install:
  - ./contrib/travis/before-install.sh
install:
  - ./contrib/travis/install.sh
script:
  - ./contrib/travis/build-and-test.sh
