//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\CalcLang.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace SharpIrcBot.Plugins.Calc.Language {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class CalcLangParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, Whitespaces=9, 
		Decimal=10, Identifier=11, Integer=12, Integer10=13, Integer16=14, Integer8=15, 
		Integer2=16;
	public const int
		RULE_expression = 0, RULE_arglist = 1;
	public static readonly string[] ruleNames = {
		"expression", "arglist"
	};

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", "'-'", "'**'", "'*'", "'/'", "'+'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, "Whitespaces", "Decimal", 
		"Identifier", "Integer", "Integer10", "Integer16", "Integer8", "Integer2"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "CalcLang.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static CalcLangParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public CalcLangParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public CalcLangParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	 
		public ExpressionContext() { }
		public virtual void CopyFrom(ExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class DivContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public DivContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.EnterDiv(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.ExitDiv(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcLangVisitor<TResult> typedVisitor = visitor as ICalcLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDiv(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AddContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public AddContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.EnterAdd(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.ExitAdd(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcLangVisitor<TResult> typedVisitor = visitor as ICalcLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAdd(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NegContext : ExpressionContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public NegContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.EnterNeg(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.ExitNeg(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcLangVisitor<TResult> typedVisitor = visitor as ICalcLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNeg(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class SubContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public SubContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.EnterSub(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.ExitSub(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcLangVisitor<TResult> typedVisitor = visitor as ICalcLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSub(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DecContext : ExpressionContext {
		public ITerminalNode Decimal() { return GetToken(CalcLangParser.Decimal, 0); }
		public DecContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.EnterDec(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.ExitDec(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcLangVisitor<TResult> typedVisitor = visitor as ICalcLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDec(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FuncContext : ExpressionContext {
		public ITerminalNode Identifier() { return GetToken(CalcLangParser.Identifier, 0); }
		public ArglistContext arglist() {
			return GetRuleContext<ArglistContext>(0);
		}
		public FuncContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.EnterFunc(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.ExitFunc(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcLangVisitor<TResult> typedVisitor = visitor as ICalcLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunc(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class CstContext : ExpressionContext {
		public ITerminalNode Identifier() { return GetToken(CalcLangParser.Identifier, 0); }
		public CstContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.EnterCst(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.ExitCst(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcLangVisitor<TResult> typedVisitor = visitor as ICalcLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCst(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MulContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public MulContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.EnterMul(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.ExitMul(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcLangVisitor<TResult> typedVisitor = visitor as ICalcLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMul(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ParensContext : ExpressionContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ParensContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.EnterParens(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.ExitParens(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcLangVisitor<TResult> typedVisitor = visitor as ICalcLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParens(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class PowContext : ExpressionContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public PowContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.EnterPow(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.ExitPow(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcLangVisitor<TResult> typedVisitor = visitor as ICalcLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPow(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IntContext : ExpressionContext {
		public ITerminalNode Integer() { return GetToken(CalcLangParser.Integer, 0); }
		public IntContext(ExpressionContext context) { CopyFrom(context); }
		public override void EnterRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.EnterInt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.ExitInt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcLangVisitor<TResult> typedVisitor = visitor as ICalcLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 0;
		EnterRecursionRule(_localctx, 0, RULE_expression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 20;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				{
				_localctx = new ParensContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 5; Match(T__0);
				State = 6; expression(0);
				State = 7; Match(T__1);
				}
				break;
			case 2:
				{
				_localctx = new FuncContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 9; Match(Identifier);
				State = 10; Match(T__0);
				State = 12;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__0) | (1L << T__2) | (1L << Decimal) | (1L << Identifier) | (1L << Integer))) != 0)) {
					{
					State = 11; arglist();
					}
				}

				State = 14; Match(T__1);
				}
				break;
			case 3:
				{
				_localctx = new NegContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 15; Match(T__2);
				State = 16; expression(9);
				}
				break;
			case 4:
				{
				_localctx = new CstContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 17; Match(Identifier);
				}
				break;
			case 5:
				{
				_localctx = new IntContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 18; Match(Integer);
				}
				break;
			case 6:
				{
				_localctx = new DecContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 19; Match(Decimal);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 39;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 37;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
					case 1:
						{
						_localctx = new PowContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 22;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 23; Match(T__3);
						State = 24; expression(9);
						}
						break;
					case 2:
						{
						_localctx = new MulContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 25;
						if (!(Precpred(Context, 7))) throw new FailedPredicateException(this, "Precpred(Context, 7)");
						State = 26; Match(T__4);
						State = 27; expression(8);
						}
						break;
					case 3:
						{
						_localctx = new DivContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 28;
						if (!(Precpred(Context, 6))) throw new FailedPredicateException(this, "Precpred(Context, 6)");
						State = 29; Match(T__5);
						State = 30; expression(7);
						}
						break;
					case 4:
						{
						_localctx = new AddContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 31;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						State = 32; Match(T__6);
						State = 33; expression(6);
						}
						break;
					case 5:
						{
						_localctx = new SubContext(new ExpressionContext(_parentctx, _parentState));
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 34;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 35; Match(T__2);
						State = 36; expression(5);
						}
						break;
					}
					} 
				}
				State = 41;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ArglistContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ArglistContext arglist() {
			return GetRuleContext<ArglistContext>(0);
		}
		public ArglistContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arglist; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.EnterArglist(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICalcLangListener typedListener = listener as ICalcLangListener;
			if (typedListener != null) typedListener.ExitArglist(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICalcLangVisitor<TResult> typedVisitor = visitor as ICalcLangVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArglist(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArglistContext arglist() {
		ArglistContext _localctx = new ArglistContext(Context, State);
		EnterRule(_localctx, 2, RULE_arglist);
		try {
			State = 47;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 42; expression(0);
				State = 43; Match(T__7);
				State = 44; arglist();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 46; expression(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 0: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 8);
		case 1: return Precpred(Context, 7);
		case 2: return Precpred(Context, 6);
		case 3: return Precpred(Context, 5);
		case 4: return Precpred(Context, 4);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x12', '\x34', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x5', '\x2', '\xF', 
		'\n', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x5', '\x2', '\x17', '\n', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\a', '\x2', '(', 
		'\n', '\x2', '\f', '\x2', '\xE', '\x2', '+', '\v', '\x2', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x5', '\x3', 
		'\x32', '\n', '\x3', '\x3', '\x3', '\x2', '\x3', '\x2', '\x4', '\x2', 
		'\x4', '\x2', '\x2', '\x2', '=', '\x2', '\x16', '\x3', '\x2', '\x2', '\x2', 
		'\x4', '\x31', '\x3', '\x2', '\x2', '\x2', '\x6', '\a', '\b', '\x2', '\x1', 
		'\x2', '\a', '\b', '\a', '\x3', '\x2', '\x2', '\b', '\t', '\x5', '\x2', 
		'\x2', '\x2', '\t', '\n', '\a', '\x4', '\x2', '\x2', '\n', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\v', '\f', '\a', '\r', '\x2', '\x2', '\f', '\xE', 
		'\a', '\x3', '\x2', '\x2', '\r', '\xF', '\x5', '\x4', '\x3', '\x2', '\xE', 
		'\r', '\x3', '\x2', '\x2', '\x2', '\xE', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\xF', '\x10', '\x3', '\x2', '\x2', '\x2', '\x10', '\x17', '\a', '\x4', 
		'\x2', '\x2', '\x11', '\x12', '\a', '\x5', '\x2', '\x2', '\x12', '\x17', 
		'\x5', '\x2', '\x2', '\v', '\x13', '\x17', '\a', '\r', '\x2', '\x2', '\x14', 
		'\x17', '\a', '\xE', '\x2', '\x2', '\x15', '\x17', '\a', '\f', '\x2', 
		'\x2', '\x16', '\x6', '\x3', '\x2', '\x2', '\x2', '\x16', '\v', '\x3', 
		'\x2', '\x2', '\x2', '\x16', '\x11', '\x3', '\x2', '\x2', '\x2', '\x16', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\x16', '\x14', '\x3', '\x2', '\x2', 
		'\x2', '\x16', '\x15', '\x3', '\x2', '\x2', '\x2', '\x17', ')', '\x3', 
		'\x2', '\x2', '\x2', '\x18', '\x19', '\f', '\n', '\x2', '\x2', '\x19', 
		'\x1A', '\a', '\x6', '\x2', '\x2', '\x1A', '(', '\x5', '\x2', '\x2', '\v', 
		'\x1B', '\x1C', '\f', '\t', '\x2', '\x2', '\x1C', '\x1D', '\a', '\a', 
		'\x2', '\x2', '\x1D', '(', '\x5', '\x2', '\x2', '\n', '\x1E', '\x1F', 
		'\f', '\b', '\x2', '\x2', '\x1F', ' ', '\a', '\b', '\x2', '\x2', ' ', 
		'(', '\x5', '\x2', '\x2', '\t', '!', '\"', '\f', '\a', '\x2', '\x2', '\"', 
		'#', '\a', '\t', '\x2', '\x2', '#', '(', '\x5', '\x2', '\x2', '\b', '$', 
		'%', '\f', '\x6', '\x2', '\x2', '%', '&', '\a', '\x5', '\x2', '\x2', '&', 
		'(', '\x5', '\x2', '\x2', '\a', '\'', '\x18', '\x3', '\x2', '\x2', '\x2', 
		'\'', '\x1B', '\x3', '\x2', '\x2', '\x2', '\'', '\x1E', '\x3', '\x2', 
		'\x2', '\x2', '\'', '!', '\x3', '\x2', '\x2', '\x2', '\'', '$', '\x3', 
		'\x2', '\x2', '\x2', '(', '+', '\x3', '\x2', '\x2', '\x2', ')', '\'', 
		'\x3', '\x2', '\x2', '\x2', ')', '*', '\x3', '\x2', '\x2', '\x2', '*', 
		'\x3', '\x3', '\x2', '\x2', '\x2', '+', ')', '\x3', '\x2', '\x2', '\x2', 
		',', '-', '\x5', '\x2', '\x2', '\x2', '-', '.', '\a', '\n', '\x2', '\x2', 
		'.', '/', '\x5', '\x4', '\x3', '\x2', '/', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\x30', '\x32', '\x5', '\x2', '\x2', '\x2', '\x31', ',', '\x3', 
		'\x2', '\x2', '\x2', '\x31', '\x30', '\x3', '\x2', '\x2', '\x2', '\x32', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '\a', '\xE', '\x16', '\'', ')', '\x31',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace SharpIrcBot.Plugins.Calc.Language
